### ISSUE TITLE
Crear clase para lectura de archivos ini

### ISSUE THREAD

**Issue by adrigm** [genbetadev/Genbeta-Dev-Engine#2]
El engine se basará en archivos estilo ini para la configuración de los diferentes aspectos por lo que necesitamos poder leer este tipo de archivos.

**Comment by edoren** [comment]
Que tal hacer uso de JSON para hacer los archivos de configuración?

**Comment by Theadd** [comment]
los archivos de configuración (*.ini) inicialmente están pensados para poder ser editados por los usuarios incluso teniendo una ventana de configuración que te simplifique el proceso, JSON esta pensado para el intercambio de datos, especializado en intercambiar objetos además de simples valores. IMHO.

**Comment by adrigm** [comment]
Como bien dice Theadd el uso de ini es más adecuado para archivos de configuración por ser fácilmente editables con un editor de texto.

**Comment by e-osuna-g** [comment]
Los ini son asi no
conf1 = valor  \n
conf2 = valor \n
conf3 = valor \n
o me equivoco?

**Comment by carlosreig** [comment]
Hola Cuauth,

Los .ini son como tú dices. En este artículo de GenbetaDev está detallada su estructura así como su manejo con C++ (http://www.genbetadev.com/cc/como-se-hace-en-c-manejo-de-ficheros-de-configuracion).

Un saludo,
Carlos

**Comment by edoren** [comment]
A ok, no sabia la diferencia entre los dos, gracias :).

**Comment by GutierrezDev** [comment]
Hola a todos: no se podria hacer con XML?

**Comment by adrigm** [comment]
@GutierrezDev, estamos en el mismo caso que JSON. No son documentos para la edición fácil en un editor de texto. XML y JSON están genial para transmitir información entre aplicaciones, pero si queremos permitir la interacción humana, mejor ini.

**Comment by RdlP** [comment]
Que diferencia habrá entre este clase y la clase ConfigReader que ya está dentro del proyecto?

**Comment by adrigm** [comment]
@RdlP la clase que hay dentro del proyecto es esta, la añadí yo y olvide cerrar el issue.

Cierro.
