### ISSUE TITLE
Licencia del Proyecto

### ISSUE THREAD

**Issue by RdlP** [genbetadev/Genbeta-Dev-Engine#21]
Creo que es importante que todo proyecto tenga una licencia, así que creo que debemos decidir el tipo de licencia que va a tener el proyecto.

**Comment by adrigm** [comment]
La tenemos: https://github.com/genbetadev/Genbeta-Dev-Engine/blob/master/LICENSE

He decidido usar la del MIT por ser simple, concisa y muy permisible. Si tenéis alguna objección ya tenemos canal de debate :)

**Comment by RdlP** [comment]
Que fallo, no la había visto. Por mi vale, de hecho estaba pensando en una MIT o BSD (que prácticamente son iguales)

**Comment by adrigm** [comment]
Ya que nadie tiene pegas, cierro.
