### ISSUE TITLE
Problema con codelite en Linux (Ubuntu)

### ISSUE THREAD

**Issue by RdlP** [genbetadev/Genbeta-Dev-Engine#32]
Buenas,

tengo un problema con codelite y con linux, resulta que cuando intento ejecutar el proyecto (dándole al botón de PLAY verde de arriba a la izquierda) me dice lo siguiente:

"Debugger exited with the following error string:
"No se especific\303\263 un archivo ejecutable.
Use la orden \302\253file\302\273 o \302\253exec-file\302\273.""

Parece ser como si tuviese que especificar el fichero de salida, pero la verdad no se en donde tengo que hacerlo...

¿Alguna idea? ¿Como puedo configurar el proyecto para que me vaya en codelite en Linux?

**Comment by RdlP** [comment]
Me acabo de fijar y previamente me da una serie de errores:

/usr/bin/ld: no se puede encontrar -lGDE-d
/usr/bin/ld: no se puede encontrar -lsfml-system
/usr/bin/ld: no se puede encontrar -lsfml-graphics
/usr/bin/ld: no se puede encontrar -lsfml-audio

Aunque realmente he añadido las librerías al path, tanto los includes como los lib. Si alguien se anima a hacer un tutorial para echarlo a andar en codelite estaría bastante bien.

**Comment by DavidBM** [comment]
Prueba a poner en la linea de compilación "-L/directorio/a/alas/librerias" Así se incluirán las librerias en el linker.

**Comment by RdlP** [comment]
Vale, muchas gracias, mañana lo probaré a ver que tal

**Comment by adrigm** [comment]
Has instalado las bibliotecas en el sistema? En Linux lo he preparado para que las tome de la instalación en el sistema.

Tengo que poner el tutorial.

**Comment by RdlP** [comment]
No, tengo los include y las librerias de sfml en una carpeta en el escritorio, aunque como he dicho he configurado el proyecto para que busque en dichas carpetas, mañana miraré con más detenimiento.

**Comment by RdlP** [comment]
Vale, he conseguido solucionar la mayoría de los errores de arriba, pero me sigue saliendo este error:

/usr/bin/ld: no se puede encontrar -lGDE-d

¿Alguna idea?

**Comment by adrigm** [comment]
@RdlP prueba a instalar SFML siguiendo el tutorial que he dejado en la wiki y utilizando el proyecto de Codelite tal cual lo tengo en el repositorio.

**Comment by adrigm** [comment]
Por cierto si no te encuentra las librerías una vez instaladas prueba a hacer:

```
$ sudo ldconfig
```

**Comment by RdlP** [comment]
Acabo de instalar sfml desde las fuentes siguiendo el tutorial. Le he hecho un git clone a este repositorio por si el mio estuviese mal configurado y a la hora de compilar me sigue saliendo el mensaje:

```
Debugger exited with the following error string:
"No se especific\303\263 un archivo ejecutable.
Use la orden \302\253file\302\273 o \302\253exec-file\302\273."
```

y en los errores de compilación me pone.

```
/usr/bin/ld: no se puede encontrar -lGDE-d
```

He hecho

```
sudo ldconfig
```

Por si acaso fuese eso y nada....

¿Alguien que tenga linux podría probar el proyecto en codelite (menos adrián que a él le funciona) y decir si lo hace funcionar? y en caso afirmativo que me explique como lo ha hecho

**Comment by adrigm** [comment]
Una cosa, primero debes compilar GDE (pica dos veces en la carpeta de GDE  en el explorador de proyectos de codelite hasta que se ponga en verde y compila).

Ahora pica dos veces en el proyecto Test para seleccionarlo y compila este también y ejecuta

Es decir, primero compila la biblioteca y luego el ejecutable

**Comment by RdlP** [comment]
Ya está solucionado, era eso @adrigm . 

Muchas Gracias

**Comment by adrigm** [comment]
Tengo que mirar si Codelite tiene la opcion de compilación a nivel de Workspace y dependencia de proyectos como Visual Studio para que no pasen estas cosas.

Cierro ;)
