### ISSUE TITLE
Ignorar compilaciones

### ISSUE THREAD

**Issue by e-osuna-g** [genbetadev/Genbeta-Dev-Engine#34]
Cada vez que hago una compilación, y me marca error, estos se ponen como commits para git, ¿no seria mejor ignorar estos archivos para que no se suban?
(Disculpen la mala ortografía , y aun no se como poner tags)

**Comment by ficion** [comment]
Bueno, no sé si lo sabrás, pero hay un archivo llamado `.gitignore` que se puede colocar en los repositorios que usen Git. Éste archivo lista una serie de parámetros de archivo, que harán que estos archivos sean ignorados por GIt (por ejemplo: ignora todos los `.png`; ignora el archivo `Thumbs.db`; ignora todo lo que hay en `/build`; etc); éste repositorio tiene un archivo `.gitignore`:

https://github.com/genbetadev/Genbeta-Dev-Engine/blob/master/.gitignore

Es bastante completo e incluye los archivos que normalmente podrían salir de una compilación
Se supone que cuando clonaste este repositorio, también debiste haberlo recibido (¿quizá debas hacer `git pull`?); ¿qué clase de archivos siguen siendo marcados para _commits_? Sería útil saberlo, para también agregarlos al `.gitignore`.

**Comment by e-osuna-g** [comment]
acabo de hacer un build y no me apareció un cambio, tal ves yo hice unos cambios a los archivos y no me di cuenta, disculpa.

**Comment by ficion** [comment]
No te disculpes (?), a todos nos pasa.

**Comment by e-osuna-g** [comment]
mmm podrías agregarme en gmail o alguna mensajería que uses?,
me gustaría tener un poco de asesoría si no te molesta en lo que voy empezando, los ultimos 2 años he estado trabajado con puro scripting de lado del servidor y es la primera vez que me meto con c++ y ando un poco perdido.
si no te molesta mi correo es este ernesto.osuna.garzon@gmail.com

**Comment by adrigm** [comment]
Como bien ha dicho @ficion para eso tenemos el gitignore, se va actualizando con las exclusiones necesarias.
