### ISSUE TITLE
Codificación de caracteres

### ISSUE THREAD

**Issue by ficion** [genbetadev/Genbeta-Dev-Engine#37]
Por lo general este tema no importa en proyectos en otros idiomas, pero como aquí usamos Español para los comentarios y mensajes, _debemos_ usar una codificación común, para que no haya problemas cuando alguien edite los archivos.

El problema, creo, pasa con Windows usado UTF8 con BOM. Propongo que la codificación del proyecto sea **UTF8 sin BOM**.

**Comment by adrigm** [comment]
Estoy de acuerdo.

**Comment by RicardoRB** [comment]
Me parece correcto :+1:

**Comment by angelnavarro** [comment]
Yo veo esta información candidata para la Wiki o la FAQ. Entiendo que evitará más de un malentendido. ¿Como lo veis?

Saludos,

**Comment by adrigm** [comment]
@angelnavarro Correcto, ¿Te animas? Hay tantos frentes abierto que o me ayudáis o poco a poco jeje.

**Comment by angelnavarro** [comment]
Pues me encantaría porque estoy deseando colaborar con algo, pero hay algo que no tengo claro XD. ¿Sería tan sencillo como poner "los ficheros deben ir con....." o habría que incluir ejemplos de cómo configurarlos según el IDE...? Si es lo primero me pongo con ello :-)

**Comment by adrigm** [comment]
Confiemos en que todo el mundo sepa cambiar la codificación de caracteres en sus respectivos IDEs ;)

**Comment by angelnavarro** [comment]
No tenía claro donde ponerlo así que he creado una página nueva. Pensé ponerlo en la FAQ pero he visto que actualmente no hay información técnica por eso he optado por una página nueva. En cualquier caso, si pensais que no es el lugar adecuado, decídmelo y lo muevo ;-)
