### ISSUE TITLE
Log.cpp refactor

### ISSUE THREAD

**Issue by fvioz** [genbetadev/Genbeta-Dev-Engine#43]
Hola a todos, 

Aunque no he manejando este lenguaje hace mucho tiempo quisiera ayudarlos haciendo code review de los códigos para hacer este proyecto mas fácil de leer y mantener.

Los códigos a continuación son prácticamente los mismos, les recomiendo implementar un método el cual reciba el tipo de la linea L45 y el mensaje de la linea L36 y sean llamado por cada funcion para hacer el log:
- [ ] https://github.com/genbetadev/Genbeta-Dev-Engine/blob/master/src/GDE/Core/Log.cpp#L34-L46
- [ ] https://github.com/genbetadev/Genbeta-Dev-Engine/blob/master/src/GDE/Core/Log.cpp#L51-L63
- [ ] https://github.com/genbetadev/Genbeta-Dev-Engine/blob/master/src/GDE/Core/Log.cpp#L68-L80

**Comment by adrigm** [comment]
Muchas gracias @fvioz, eso mismo estamos discutiendo e implementando em el issue #20
