### ISSUE TITLE
Crear TODO.

### ISSUE THREAD

**Issue by dsocolobsky** [genbetadev/Genbeta-Dev-Engine#46]
Buenas.

Soy nuevo en este proyecto, hace ya tiempo que estoy buscando un buen proyecto al que unirme y trabajar en equipo, y como lector de Genbeta Dev me acabo de enterar de  esto, ademas es perfecto ya que me interesa el tema y he usado SFML.

Me gustaría contribuir pero no tengo ni idea de que hay por hacer, asi que propongo tener un fichero llamado TODO donde se vayan añadiendo las cosas que hay por implementar y/o cambiar.

O quizá eso ya exista y no este mirando en el lugar apropiado.

Gracias.

**Comment by adrigm** [comment]
Estás en él. Esta lista de issues son cosas pendientes por hacer, de ella por supuesto saldrán muchas más, pero cuando se vayan abordando se irán ampliando. Escoge una que te interese y a colaborar ;)

**Comment by ficion** [comment]
Aprovechando el thread; aún cuando la pregunta es off-topic (bastante): ¿En qué yo podría ayudar? Me gustaría mucho colaborar, pero sólo sé C y un poco de _bash scripting_. ¿Hay algo en lo que pueda ayudar con esos pocos conocimientos? (Tengo que ponerme el día con C++, pero no quiero colaborar con algo que no tengo idea).

**Comment by adrigm** [comment]
@ficion hay tareas que hacer: documentar las clases al estilo doxygen, revisar que se cumple la guía de estilo, aportar ideas para el proyecto, difundir el proyecto...

**Comment by ficion** [comment]
@adrigm Hice algunos cambios en la Wiki.

**Comment by adrigm** [comment]
Cierro este hilo para mantener el orden.
