### ISSUE TITLE
Logotipo o imagen del GDE

### ISSUE THREAD

**Issue by Pedro-vk** [genbetadev/Genbeta-Dev-Engine#50]
Hola, quería preguntar si alguien se ha puesto o ha pensado en la parte de la imagen del GDE (como logotipo y demás).

El cartelito de @adrigm yo lo veo como una buena base para el logo: http://img.genbetadev.com/2013/10/logoGDE.png ... 

¿Qué opináis los demás?

**Comment by adrigm** [comment]
Mis dotes artísticas no son muy buenas, seguro que alguien puede hacer algo mejor. Pero se puede tomar de base, sí.

**Comment by Pedro-vk** [comment]
Lo interesante sería, entre todos, definir como podría ser el logo o como podríamos plantear la imagen, una vez hecho eso, si nadie se anima podría ponerme yo a hacer el logotipo de varias formas.

**Comment by adrigm** [comment]
Sería interesante, en el proyecto SFML cuando se debatió sobre el nuevo logo varios usuarios enviaron propuestas y luego se voto, podría ser interesante.

**Comment by texter** [comment]
No es mala idea como base. Secundo la idea.

**Comment by angelnavarro** [comment]
Podríamos hacer un mini-concurso :-D (en caso de que haya más de un candidato)

**Comment by adrigm** [comment]
A ver si hay alguno por lo menos que se ofrezca... jeje

**Comment by Pedro-vk** [comment]
¿Podrías destinar una carpeta para esta parte?, para poner las diferentes propuestas en un mismo lugar.
Aunque también podemos poner links en este mismo hilo...

**Comment by adrigm** [comment]
Mejor mantenerlo ajeno al proyecto hasta que tengamos uno definitivo. Me parece buena idea usar este hilo para que casa uno ponga links a sus creaciones e ir haciendo una votación improvisada.

**Comment by Pedro-vk** [comment]
Bueno, lanzo mi primera propuesta rápida (aunque se debería de pulir, creo que es una buena propuesta para empezar a debatir).

Logo: http://lab.xitrus.es/GDE/logo/logo01.png
Con letra:
http://lab.xitrus.es/GDE/logo/logo01-1.png (mediano)
http://lab.xitrus.es/GDE/logo/logo01-2.png (grande)

Se podría probar en la misma letra del "GD" poner "GDE" o pasarlo a denominar como está en la imagen de los post: "GENBETA:dev GAME:engine",

**Comment by adrigm** [comment]
El uso de Genbeta Dev Engine sobre Genbeta Dev Game Engine que quizás sería más correcto fue precisamente para tener un nombre corto GDE en lugar de GDGE. Sobre todo para el uso del namespace GDE::

Me gusta tu logo, a ver si salen más candidatos, sino, ya tenemos nuevo logo xD

**Comment by ficion** [comment]
@Pedro-vk ¡Está muy bueno! Si me preguntas luce muy bien y lo mejor es que se pueden cambiar los colores e irá bien.

**Comment by Pedro-vk** [comment]
Aún así, partiendo de la misma estructura haré varias propuestas, con otros colores y combinaciones de formas.
Probaré a darle un estilo "flat design", por probar algo... xD si tengo tiempo hago una tira larga... como luego hay que votar...
