### ISSUE TITLE
Librería estática o dinámica?

### ISSUE THREAD

**Issue by edoren** [genbetadev/Genbeta-Dev-Engine#54]
Es algo que se debería definir en el proyecto, para mi lo ideal seria que se pudiera generar de las dos formas ya que SFML da la posibilidad de trabajar de las dos maneras. Que opinan?

**Comment by adrigm** [comment]
Se dará las opciones de los dos, ya el proyecto está preparado para soportar los dos métodos, es lazón de que todas las clases tengan la macro GDE_API

**Comment by edoren** [comment]
Ok, entonces me imagino que se va a agregar el sufijo `-s` al nombre de la librería, cuando se cree estática, algo parecido a lo que hace SFML.
