### ISSUE TITLE
Integración con XCode

### ISSUE THREAD

**Issue by sawbona** [genbetadev/Genbeta-Dev-Engine#6]
Hola.
Es la primera vez que utilizo los Issues de Github.
Mi duda/comentario es, me gustaría integrar el proyecto dentro de XCode para hacerlo funcionar en Mac e iOS, entonces, ¿qué sugieres que sea lo mejor? ¿Hacer un fork del proyecto para esto o tratar de hacerlo dentro del mismo?
Saludos y seguiré de cerca este proyecto.
PD. ¿cómo marco un Issue con el tag de question?

**Comment by edoren** [comment]
Lastimosamente SFML no tiene soporte aún para iOS, pero ya está anunciado para la version 2.2 que según el creador para finales de este año sale. No he trabajado con MacOSX, pero puedes seguir este tutorial de la página de SFML donde explican como construir un proyecto de SFML en XCode para que te des una idea http://sfml-dev.org/tutorials/2.1/start-osx.php

**Comment by adrigm** [comment]
La filosofía de Github es que tu haces un Fork del proyecto y haces los cambios ahí hasta que funcione. Entonces solicitas un Pull Request y se incorporan tus cambios al proyecto principal.

Cuenta con mi ayuda para esa versión de XCode, es uno de las metas propuestas y entre todos lo configuraremos.

Recuerda que todos los archivos de Xcode deberán quedar en la ruta builds/xcode

**Comment by RicardoRB** [comment]
Yo uso codeblocks con SFML, este IDE es multiplataforma y bastante rápido y completo. Lo os lo aconsejo :+1:

**Comment by sawbona** [comment]
Ok.

Entonces intentaré toquetear el fork que he hecho del proyecto para integrar SMFL siguiendo el tutorial que menciona @edoren.
Un vistazo rápido al tutorial de SFML menciona que para utilizar C++11 se tiene que tener instalado Mountain Lion (10.8), pienso que se usarán características de C++11 dentro de este proyecto, ¿cierto? En caso contrario dice que SFML es compatible desde Mac OS X Leopard (10.5). 

¿Uds que opinan? ¿Debería darse soporte desde la versión 10.5 de OSX y prescindir de C++11 o soportar C++11 y poner a la versión 10.8 como requerimiento?

**Comment by RicardoRB** [comment]
Yo he usado SFML con la C++11, y creo que depende del compilador que uses, no de la versión de de tu sistema operativo, aún así de Mac OS estoy bastante perdido.

**Comment by adrigm** [comment]
No haremos uso de C++11, intentamos que el proyecto sea lo más asequible posible para la mayoría de la gente. Ya hay muchos que tienen trabas con C++ como para meterles C++11

Recordad que es un proyecto de aprendizaje.

**Comment by rickyah** [comment]
@sawbona, ¿cómo llevas el estado de esto?, yo acabo de empezar a mirar como generar el proyecto con xcode

**Comment by adrigm** [comment]
@rickyah Creo que estaba un poco verde en el tema, si te quieres encargar, todo tuyo, a menos que @sawbona nos diga que ha avanzado en el asunto.

**Comment by rickyah** [comment]
Voy a ponerme con ello entonces, de todas maneras me viene bien a mi :+1:

**Comment by rickyah** [comment]
Lo tengo listo:

https://github.com/genbetadev/Genbeta-Dev-Engine/pull/60

Por cierto, ¿cómo se puede asignar a alguien un issue? No puedo auto-asignármelo

**Comment by StriderHND** [comment]
OK pues vamos a ver el tutorial que coloco @edoren y configurar todo este correcto para probarlo y ver en que aportamos

**Comment by rickyah** [comment]
Este issue se podría cerrar, no?
