### ISSUE TITLE
Más de la Wiki

### ISSUE THREAD

**Issue by ficion** [genbetadev/Genbeta-Dev-Engine#62]
Acabo de hacer una página "Home" para la Wiki del proyecto, de forma que la gente nueva pueda ver de forma más amigable a los que estén conociendo por primera vez este proyecto.
Creo que podría mejorar cómo la organicé, pero eso creo que es para después.

Por ahora, me gustaría pedir un poco de ayuda con los artículos que faltan:
- Cómo compilar SFML 2 en Mac OS.
- Cómo compilar GDE en Windows.
- Cómo compilar GDE en Mac OS.
- Cómo compilar GDE en GNU/Linux.
- Cómo usar Git y Github para colaborar

Por ahora, creo que esos serían necesarios. Yo me puedo encargar de los dos últimos, pero me veo algo imposibilitado de hacer el resto.

Quizá otros artículos que serán necesarios en el futuro serían títulos como:
- Cómo cargar recursos
- Cómo hacer un programa simple con GDE

Aunque esos serán necesarios cuando el proyecto crezca.

PD: Quizá el "cómo" sea algo repetitivo, por lo que habría que cambiar "Cómo usar Git y Github para colaborar" por "Usando Git y Github para colaborar".

**Comment by adrigm** [comment]
He añadido un enlace a un libro de Git gratuito para los principiantes.

**Comment by rickyah** [comment]
Genial, el pro-git es una maravilla de libro.
