### ISSUE TITLE
Dependencias de SFML

### ISSUE THREAD

**Issue by edoren** [genbetadev/Genbeta-Dev-Engine#65]
Como andamos trabajando en la versión en desarrollo de SFML, hace un mes se cambió la forma en la que se linkean las librerías estáticas de SFML https://github.com/LaurentGomila/SFML/commit/dbf01a775b7545bf83fbee0e1464f3f323723187, ahora antes de linkearlas en algún proyecto es requerido linkear las dependencias de SFML, esto supone un gran problemas mas que todo para Windows ya que es mas usual usar librerías estáticas.
Una opción que se puede dar es directamente en el proyecto, en la carpeta de `extlibs` agregar las dependencias de SFML, en el caso que se vayan a linkear SFML estáticamente.

**Comment by DavidBM** [comment]
SFML distribuye sus dependencias en su propio paquete, no?
Quiero decir, si ya las trae SFML y vamos a obligar a descargarlo a parte, con explicar como copiar las librerias dentro de nuestro proyecto tendría que ir bien.

**Comment by edoren** [comment]
Si, es la mejor opción.
