### ISSUE TITLE
Como montar los proyectos en distintos entornos

### ISSUE THREAD

**Issue by angelnavarro** [genbetadev/Genbeta-Dev-Engine#69]
Buenas,

Abro este issue por si fuera posible crear documentación sobre cómo dejar el proyecto listo para trabajar en los distintos entornos. Yo por mi parte, he creado un tutorial sobre cómo lo he hecho yo en Windows, usando Code::Blocks y MinGW. Soy nuevo con C++ y he usado muy poco Codeblocks, con lo que estoy seguro de que algún fallo tendré (ahí lo dejo por si alguien quiere revisarlo ;-)), pero lo cierto es que yo he conseguido ejecutarlo.

El documento en cuestión es este: https://github.com/genbetadev/Genbeta-Dev-Engine/wiki/Preparaci%C3%B3n-del-proyecto-en-Code::Blocks,-MingGW,-Windows

Animo desde aquí a hacer lo mismo para otros entornos.

Saludos,

**Comment by e-osuna-g** [comment]
Ami si me hace el dll del GDE pero en la parte de 
anApp->setFirstScene(new SceneMain("Main"));
||=== Test, Debug-windows ===|
obj\Debug\src\Test\main.o||In function `main':|
C:\Users\usuario\Documents\GitExt\Game\Genbeta-Dev-Engine\src\Test\main.cpp|13|undefined reference to`SceneMain::SceneMain(std::string)'|
||=== Build finished: 1 errors, 0 warnings (0 minutes, 1 seconds) ===|
me marca ese error. algun consejo de que puede ser?

**Comment by angelnavarro** [comment]
Yo te diría que parece que no te está cogiendo la libería GDE.dll, ¿la has añadido a la opciones del proyecto Test?

Saludos,

**Comment by e-osuna-g** [comment]
ahí esta
![linker con dll](https://f.cloud.github.com/assets/5857447/1563298/6c033b9a-505d-11e3-9ed1-8c112d6fd2ce.PNG)
no se si realmente  estoy haciendo algo mal

**Comment by edoren** [comment]
En realidad si hay algo malo, las librerías `.dll` son librerías de tiempo de ejecución, eso significa que solo se usan en la ejecución del programa, no para crear el programa en sí. No suelo trabajar mucho en IDEs, así que no te puedo ayudar tanto en eso, pero cuando se genera la librería compartida de GDE deberían salir dos archivos, una la `.dll` y una librería `.a`(MinGW) o `.lib`(MSVC), dependiendo del compilador. Esta ultima es la que se tiene que linkear para que el Test funcione.

**Comment by angelnavarro** [comment]
Pues si lo dice @edoren será así, aunque en mi caso no tengo dos archivos :-S. Tengo sólo uno y lo he linkado igual que ha hecho @cuauth , como tengo puesto en el tutorial

@cuauth , si no lo consigues y quieres, podemos preparar una sesión con TeamViewer e intento montártelo para que por lo menos puedas arrancar

Saludos,

**Comment by edoren** [comment]
Porque no intentas generar el proyecto con CMake?.
