### ISSUE TITLE
Build del proyecto como static o shared library

### ISSUE THREAD

**Issue by danigomez** [genbetadev/Genbeta-Dev-Engine#71]
Buenas, gente! no me está quedando del todo claro el tema del buildeo como libreria estática o dinámica...
Por ejemplo, en el archivo Config.hpp chequea la macro `GDE_STATIC` para definir `GDE_API` según sea un build como librería estática o no.
Luego está la macro `GDE_API_EXPORT`, que por lo que llego a entender deberia estar definida solo para el build del engine y para que las clases definidas por el engine sean visibles y puedan ser utilizadas por quien haga uso del mismo, es esto correcto??
Y por otro lado, dónde y cuándo deberian ser definidas estás macros?, ya que al parecer no están definidas...
Gracias!

**Comment by DavidBM** [comment]
Las macros las defines con CMake al generar el proyecto. Cuando le des a configure te saldrán las opciones a modificar.

**Comment by danigomez** [comment]
Ahhh ok, es decir, hay que definirlas a mano en el momento del build??

**Comment by DavidBM** [comment]
Sep.
El propio CMake te muestra las variables que puedes modificar agrupadas por funciones.

**Comment by edoren** [comment]
Ups, error mio jeje, no definí la macro cuando se linkea estáticamente xD, ya hago el arreglo.

**Comment by danigomez** [comment]
xD, jaja, entonces las macros se tienen que definir en CMakeList según si elegiste la opción de `BUILD_SHARED_LIBRARIES` o no?? :P, en la documentación de CMake encontré la función `add_definitions`, que aparentemente hace eso, agregar definiciones de macros a la compilación,  vas a hacerlo así??, nunca use CMake, así que hay cosas que me quedan un poco en el aire jeje

**Comment by edoren** [comment]
Si, lo haré así.
